.TH "metacall Directory Reference" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmetacall\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_allocator\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_error\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_fork\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_log\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_value\&.h\fP"
.br
.in -1c
