.TH "detour Directory Reference" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdetour\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_impl_handle\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_interface\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_singleton\&.h\fP"
.br
.in -1c
