.TH "adt Directory Reference" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adt Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadt\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_comparable\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_hash\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_set\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_set_bucket\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_trie\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_vector\&.h\fP"
.br
.in -1c
