.TH "adt Directory Reference" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adt Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadt\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_bucket\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_comparable\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_hash\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_map\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_set\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_string\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_trie\&.h\fP"
.br
.ti -1c
.RI "file \fBadt_vector\&.h\fP"
.br
.in -1c
