.TH "detour Directory Reference" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdetour\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_handle\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_interface\&.h\fP"
.br
.in -1c
