.TH "log Directory Reference" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlog\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_aspect\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_aspect_format\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_aspect_schedule\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_aspect_storage\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_aspect_stream\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_handle\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_level\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_map\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_format\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_format_binary\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_format_custom\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_format_text\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_schedule\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_schedule_async\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_schedule_sync\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_storage\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_storage_batch\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_storage_sequential\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_custom\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_file\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_nginx\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_socket\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_stdio\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_policy_stream_syslog\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_preprocessor\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_record\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_singleton\&.h\fP"
.br
.ti -1c
.RI "file \fBlog_valid_size\&.h\fP"
.br
.in -1c
