.TH "format Directory Reference" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBformat\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_print\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_specifier\&.h\fP"
.br
.in -1c
