.TH "plugin Directory Reference" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugin Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBplugin\&.h\fP"
.br
.ti -1c
.RI "file \fBplugin_descriptor\&.h\fP"
.br
.ti -1c
.RI "file \fBplugin_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBplugin_interface\&.hpp\fP"
.br
.ti -1c
.RI "file \fBplugin_loader\&.h\fP"
.br
.ti -1c
.RI "file \fBplugin_manager\&.h\fP"
.br
.in -1c
