.TH "adt.h" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adt.h
.SH SYNOPSIS
.br
.PP
\fC#include <adt/adt_api\&.h>\fP
.br
\fC#include <adt/adt_comparable\&.h>\fP
.br
\fC#include <adt/adt_hash\&.h>\fP
.br
\fC#include <adt/adt_trie\&.h>\fP
.br
\fC#include <adt/adt_vector\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const ADT_API char * \fBadt_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const ADT_API char* adt_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
