.TH "adt.h" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adt.h
.SH SYNOPSIS
.br
.PP
\fC#include <adt/adt_api\&.h>\fP
.br
\fC#include <adt/adt_comparable\&.h>\fP
.br
\fC#include <adt/adt_hash\&.h>\fP
.br
\fC#include <adt/adt_trie\&.h>\fP
.br
\fC#include <adt/adt_vector\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ADT_API const char * \fBadt_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ADT_API const char* adt_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
