.TH "adt_set_bucket.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adt_set_bucket.h
.SH SYNOPSIS
.br
.PP
\fC#include <adt/adt_api\&.h>\fP
.br
\fC#include <adt/adt_comparable\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBset_pair\fP"
.br
.ti -1c
.RI "struct \fBset_bucket\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ADT_API size_t \fBset_bucket_capacity\fP (size_t prime)"
.br
.ti -1c
.RI "ADT_API set_bucket \fBset_bucket_create\fP (size_t size)"
.br
.ti -1c
.RI "ADT_API int \fBset_bucket_alloc_pairs\fP (set_bucket bucket, size_t capacity)"
.br
.ti -1c
.RI "ADT_API int \fBset_bucket_realloc_pairs\fP (set_bucket bucket, size_t new_capacity)"
.br
.ti -1c
.RI "ADT_API set_pair \fBset_bucket_get_pair\fP (set_bucket bucket, \fBcomparable_callback\fP compare_cb, void *key)"
.br
.ti -1c
.RI "ADT_API int \fBset_bucket_insert\fP (set_bucket bucket, void *key, void *\fBvalue\fP)"
.br
.ti -1c
.RI "ADT_API int \fBset_bucket_remove\fP (set_bucket bucket, \fBcomparable_callback\fP compare_cb, void *key, void **\fBvalue\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ADT_API size_t set_bucket_capacity (size_t prime)"

.SS "ADT_API set_bucket set_bucket_create (size_t size)"

.SS "ADT_API int set_bucket_alloc_pairs (set_bucket bucket, size_t capacity)"

.SS "ADT_API int set_bucket_realloc_pairs (set_bucket bucket, size_t new_capacity)"

.SS "ADT_API set_pair set_bucket_get_pair (set_bucket bucket, \fBcomparable_callback\fP compare_cb, void * key)"

.SS "ADT_API int set_bucket_insert (set_bucket bucket, void * key, void * value)"

.SS "ADT_API int set_bucket_remove (set_bucket bucket, \fBcomparable_callback\fP compare_cb, void * key, void ** value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
