.TH "attribute_interface" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
attribute_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_attribute_decl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBattribute_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBattribute_impl_interface_destroy\fP attribute_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
