.TH "bucket" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bucket
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/adt/include/adt/adt_bucket\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "pair \fBpairs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t bucket::count"

.SS "size_t bucket::capacity"

.SS "pair bucket::pairs"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
