.TH "class_interface" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_class\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclass_impl_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_constructor\fP \fBconstructor\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_static_get\fP \fBstatic_get\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_static_set\fP \fBstatic_set\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_static_invoke\fP \fBstatic_invoke\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_static_await\fP \fBstatic_await\fP"
.br
.ti -1c
.RI "\fBclass_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBclass_impl_interface_create\fP class_interface::create"

.SS "\fBclass_impl_interface_constructor\fP class_interface::constructor"

.SS "\fBclass_impl_interface_static_get\fP class_interface::static_get"

.SS "\fBclass_impl_interface_static_set\fP class_interface::static_set"

.SS "\fBclass_impl_interface_static_invoke\fP class_interface::static_invoke"

.SS "\fBclass_impl_interface_static_await\fP class_interface::static_await"

.SS "\fBclass_impl_interface_destroy\fP class_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
