.TH "detour_interface.h" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour_interface.h
.SH SYNOPSIS
.br
.PP
\fC#include <detour/detour_api\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdetour_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBdetour_impl_handle\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBdetour_impl_handle\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
