.TH "detour_handle.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour_handle.h
.SH SYNOPSIS
.br
.PP
\fC#include <detour/detour_api\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct detour_handle_type * \fBdetour_handle\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct detour_handle_type* \fBdetour_handle\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
