.TH "detour_interface" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/detour/include/detour/detour_interface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdetour_interface_initialize\fP \fBinitialize\fP"
.br
.ti -1c
.RI "\fBdetour_interface_install\fP \fBinstall\fP"
.br
.ti -1c
.RI "\fBdetour_interface_uninstall\fP \fBuninstall\fP"
.br
.ti -1c
.RI "\fBdetour_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBdetour_interface_initialize\fP detour_interface::initialize"

.SS "\fBdetour_interface_install\fP detour_interface::install"

.SS "\fBdetour_interface_uninstall\fP detour_interface::uninstall"

.SS "\fBdetour_interface_destroy\fP detour_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
