.TH "dynlink_impl_beos.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_beos.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <dynlink/dynlink_impl_symbol_beos\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "DYNLINK_API dynlink_impl_interface \fBdynlink_impl_interface_singleton_beos\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DYNLINK_API dynlink_impl_interface dynlink_impl_interface_singleton_beos (void)"

.PP
BeOS/Haiku image add-on object implementation singleton\&. 
.PP
\fBReturns\fP
.RS 4
A pointer to the image add-on object implementation singleton 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
