.TH "dynlink_impl_interface.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_interface.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <dynlink/dynlink_impl\&.h>\fP
.br
\fC#include <dynlink/dynlink_interface\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdynlink_impl_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBdynlink_impl\fP(* \fBdynlink_impl_interface_load\fP) (\fBdynlink\fP)"
.br
.ti -1c
.RI "typedef int(* \fBdynlink_impl_interface_symbol\fP) (\fBdynlink\fP, \fBdynlink_impl\fP, \fBdynlink_symbol_name\fP, \fBdynlink_symbol_addr\fP *)"
.br
.ti -1c
.RI "typedef int(* \fBdynlink_impl_interface_unload\fP) (\fBdynlink\fP, \fBdynlink_impl\fP)"
.br
.ti -1c
.RI "typedef dynlink_impl_interface(* \fBdynlink_impl_interface_singleton\fP) (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const typedef char *(* \fBdynlink_impl_interface_extension\fP )(void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBdynlink_impl\fP(* dynlink_impl_interface_load) (\fBdynlink\fP)"

.SS "typedef int(* dynlink_impl_interface_symbol) (\fBdynlink\fP, \fBdynlink_impl\fP, \fBdynlink_symbol_name\fP, \fBdynlink_symbol_addr\fP *)"

.SS "typedef int(* dynlink_impl_interface_unload) (\fBdynlink\fP, \fBdynlink_impl\fP)"

.SS "typedef dynlink_impl_interface(* dynlink_impl_interface_singleton) (void)"

.SH "Variable Documentation"
.PP 
.SS "const typedef char*(* dynlink_impl_interface_extension) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
