.TH "dynlink_impl_win32.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_win32.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <dynlink/dynlink_impl_symbol_win32\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "DYNLINK_API dynlink_impl_interface \fBdynlink_impl_interface_singleton_win32\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DYNLINK_API dynlink_impl_interface dynlink_impl_interface_singleton_win32 (void)"

.PP
Win32 dynamic link shared object implementation singleton\&. 
.PP
\fBReturns\fP
.RS 4
A pointer to the dynamically linked shared object implementation singleton 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
