.TH "dynlink_impl_type.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_type.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBdynlink_impl\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBdynlink_impl\fP"
Dynamically linked shared object implementation 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
