.TH "dynlink_type.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_type.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <portability/portability_library_path\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct dynlink_type * \fBdynlink\fP"
.br
.ti -1c
.RI "typedef const char * \fBdynlink_path\fP"
.br
.ti -1c
.RI "typedef const char * \fBdynlink_name\fP"
.br
.ti -1c
.RI "typedef const char * \fBdynlink_symbol_name\fP"
.br
.ti -1c
.RI "typedef portability_library_path_str \fBdynlink_library_path_str\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct dynlink_type* \fBdynlink\fP"
Dynamically linked shared object handle 
.SS "typedef const char* \fBdynlink_path\fP"
Dynamically linked shared object path 
.SS "typedef const char* \fBdynlink_name\fP"
Dynamically linked shared object name 
.SS "typedef const char* \fBdynlink_symbol_name\fP"
Dynamically linked shared object symbol name 
.SS "typedef portability_library_path_str \fBdynlink_library_path_str\fP"
Dynamically linked shared object symbol name 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
