.TH "dynlink_impl_name.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_impl_name.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <portability/portability_path\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBdynlink_name_impl\fP[PORTABILITY_PATH_SIZE]"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef char dynlink_name_impl[PORTABILITY_PATH_SIZE]"
Allocated copy of dynamically linked shared object name 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
