.TH "format.h" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format.h
.SH SYNOPSIS
.br
.PP
\fC#include <format/format_api\&.h>\fP
.br
\fC#include <format/format_print\&.h>\fP
.br
\fC#include <format/format_specifier\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const FORMAT_API char * \fBformat_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const FORMAT_API char* format_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
