.TH "format_specifier.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_specifier.h
.SH SYNOPSIS
.br
.PP
\fC#include <format/format_api\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRIdS\fP   FORMAT_PREFIX 'd'"
.br
.ti -1c
.RI "#define \fBPRIxS\fP   FORMAT_PREFIX 'x'"
.br
.ti -1c
.RI "#define \fBPRIuS\fP   FORMAT_PREFIX 'u'"
.br
.ti -1c
.RI "#define \fBPRIXS\fP   FORMAT_PREFIX 'X'"
.br
.ti -1c
.RI "#define \fBPRIoS\fP   FORMAT_PREFIX 'o'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PRIdS   FORMAT_PREFIX 'd'"

.SS "#define PRIxS   FORMAT_PREFIX 'x'"

.SS "#define PRIuS   FORMAT_PREFIX 'u'"

.SS "#define PRIXS   FORMAT_PREFIX 'X'"

.SS "#define PRIoS   FORMAT_PREFIX 'o'"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
