.TH "format_print.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_print.h
.SH SYNOPSIS
.br
.PP
\fC#include <format/format_api\&.h>\fP
.br
\fC#include <format/format_specifier\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
