.TH "function_interface" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
function_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_function\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfunction_impl_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBfunction_impl_interface_invoke\fP \fBinvoke\fP"
.br
.ti -1c
.RI "\fBfunction_impl_interface_await\fP \fBawait\fP"
.br
.ti -1c
.RI "\fBfunction_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfunction_impl_interface_create\fP function_interface::create"

.SS "\fBfunction_impl_interface_invoke\fP function_interface::invoke"

.SS "\fBfunction_impl_interface_await\fP function_interface::await"

.SS "\fBfunction_impl_interface_destroy\fP function_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
