.TH "future_interface" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
future_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_future\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfuture_impl_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBfuture_impl_interface_await\fP \fBawait\fP"
.br
.ti -1c
.RI "\fBfuture_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfuture_impl_interface_create\fP future_interface::create"

.SS "\fBfuture_impl_interface_await\fP future_interface::await"

.SS "\fBfuture_impl_interface_destroy\fP future_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
