.TH "loader_impl_descriptor.h" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_descriptor.h
.SH SYNOPSIS
.br
.PP
\fC#include <loader/loader_descriptor\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBloader_impl_descriptor\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef loader_descriptor(* \fBloader_impl_descriptor_instance\fP) (void)"
.br
.ti -1c
.RI "typedef loader_impl_descriptor(* \fBloader_impl_descriptor_singleton\fP) (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef loader_descriptor(* loader_impl_descriptor_instance) (void)"

.SS "typedef loader_impl_descriptor(* loader_impl_descriptor_singleton) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
