.TH "loader_descriptor_version" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_descriptor_version
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint32_t \fBnumber\fP"
.br
.ti -1c
.RI "const char * \fBstr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const uint32_t loader_descriptor_version::number"
Version number on unsigned integer (hexadecimal) 
.SS "const char* loader_descriptor_version::str"
Version string (human readable) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
