.TH "loader_descriptor_copyright" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_descriptor_copyright
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBauthors\fP"
.br
.ti -1c
.RI "const char * \fBowners\fP"
.br
.ti -1c
.RI "const char * \fBwebpage\fP"
.br
.ti -1c
.RI "struct \fBloader_descriptor_date_type\fP \fBdate\fP"
.br
.ti -1c
.RI "const char * \fBorganization\fP"
.br
.ti -1c
.RI "const char * \fBmaintainers\fP"
.br
.ti -1c
.RI "struct \fBloader_descriptor_version_type\fP \fBversion\fP"
.br
.ti -1c
.RI "const char * \fBlicense\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* loader_descriptor_copyright::authors"
Authors of the loader 
.SS "const char* loader_descriptor_copyright::owners"
Owners of the loader 
.SS "const char* loader_descriptor_copyright::webpage"
Web of the loader developers 
.SS "struct \fBloader_descriptor_date_type\fP loader_descriptor_copyright::date"
Date in which the loader was created 
.SS "const char* loader_descriptor_copyright::organization"
Organization name under loader is developed 
.SS "const char* loader_descriptor_copyright::maintainers"
Current maintainers of the loader 
.SS "struct \fBloader_descriptor_version_type\fP loader_descriptor_copyright::version"
Current version of the loader 
.SS "const char* loader_descriptor_copyright::license"
License of the loader 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
