.TH "loader_env.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_env.h
.SH SYNOPSIS
.br
.PP
\fC#include <loader/loader_api\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "LOADER_API void \fBloader_env_initialize\fP (void)"
.br
.ti -1c
.RI "const LOADER_API char * \fBloader_env_script_path\fP (void)"
.br
.ti -1c
.RI "const LOADER_API char * \fBloader_env_library_path\fP (void)"
.br
.ti -1c
.RI "LOADER_API void \fBloader_env_destroy\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LOADER_API void loader_env_initialize (void)"

.SS "const LOADER_API char* loader_env_script_path (void)"

.SS "const LOADER_API char* loader_env_library_path (void)"

.SS "LOADER_API void loader_env_destroy (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
