.TH "loader_impl_descriptor" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_impl_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBloader_impl_descriptor_instance\fP \fBdescriptor\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBloader_impl_descriptor_instance\fP loader_impl_descriptor::descriptor"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
