.TH "loader_descriptor_platform" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_descriptor_platform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBarchitecture\fP"
.br
.ti -1c
.RI "const char * \fBcompiler\fP"
.br
.ti -1c
.RI "const char * \fBoperative_system\fP"
.br
.ti -1c
.RI "const char * \fBfamily\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* loader_descriptor_platform::architecture"
Architecture where loader was compiled 
.SS "const char* loader_descriptor_platform::compiler"
Compiler used to build the loader 
.SS "const char* loader_descriptor_platform::operative_system"
Operative system under loader was compiled 
.SS "const char* loader_descriptor_platform::family"
Platform family which operative system belongs to 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
