.TH "loader_impl_interface" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_impl_interface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBloader_impl_interface_initialize\fP \fBinitialize\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_execution_path\fP \fBexecution_path\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_load_from_file\fP \fBload_from_file\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_load_from_memory\fP \fBload_from_memory\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_load_from_package\fP \fBload_from_package\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_clear\fP \fBclear\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_discover\fP \fBdiscover\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBloader_impl_interface_initialize\fP loader_impl_interface::initialize"

.SS "\fBloader_impl_interface_execution_path\fP loader_impl_interface::execution_path"

.SS "\fBloader_impl_interface_load_from_file\fP loader_impl_interface::load_from_file"

.SS "\fBloader_impl_interface_load_from_memory\fP loader_impl_interface::load_from_memory"

.SS "\fBloader_impl_interface_load_from_package\fP loader_impl_interface::load_from_package"

.SS "\fBloader_impl_interface_clear\fP loader_impl_interface::clear"

.SS "\fBloader_impl_interface_discover\fP loader_impl_interface::discover"

.SS "\fBloader_impl_interface_destroy\fP loader_impl_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
