.TH "loader_handle.h" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_handle.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBloader_handle\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBloader_handle\fP"

.PP
Generic handle for run-time loaded code\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
