.TH "loader_descriptor" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBkeyword\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "loader_descriptor_copyright \fBcopyright\fP"
.br
.ti -1c
.RI "loader_descriptor_language \fBlanguage\fP"
.br
.ti -1c
.RI "loader_descriptor_technology \fBtechnology\fP"
.br
.ti -1c
.RI "loader_descriptor_platform \fBplatform\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* loader_descriptor::name"
Loader name 
.SS "const char* loader_descriptor::keyword"
Loader identifier 
.SS "const char* loader_descriptor::description"
Loader description 
.SS "loader_descriptor_copyright loader_descriptor::copyright"
Copyright information 
.SS "loader_descriptor_language loader_descriptor::language"
Loader language information 
.SS "loader_descriptor_technology loader_descriptor::technology"
Loader technology information 
.SS "loader_descriptor_platform loader_descriptor::platform"
Platform information 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
