.TH "loader_impl_data.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_data.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBloader_impl_data\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBloader_impl_data\fP"

.PP
Generic handle for implementation data of a loader\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
