.TH "loader_naming.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_naming.h
.SH SYNOPSIS
.br
.PP
\fC#include <loader/loader_api\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOADER_NAMING_PATH_SIZE\fP   0x01FF"
.br
.ti -1c
.RI "#define \fBLOADER_NAMING_NAME_SIZE\fP   0xFF"
.br
.ti -1c
.RI "#define \fBLOADER_NAMING_TAG_SIZE\fP   0x40"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBloader_naming_path\fP[\fBLOADER_NAMING_PATH_SIZE\fP]"
.br
.ti -1c
.RI "typedef char \fBloader_naming_name\fP[\fBLOADER_NAMING_NAME_SIZE\fP]"
.br
.ti -1c
.RI "typedef char \fBloader_naming_tag\fP[\fBLOADER_NAMING_TAG_SIZE\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOADER_NAMING_PATH_SIZE   0x01FF"

.SS "#define LOADER_NAMING_NAME_SIZE   0xFF"

.SS "#define LOADER_NAMING_TAG_SIZE   0x40"

.SH "Typedef Documentation"
.PP 
.SS "typedef char loader_naming_path[\fBLOADER_NAMING_PATH_SIZE\fP]"

.SS "typedef char loader_naming_name[\fBLOADER_NAMING_NAME_SIZE\fP]"

.SS "typedef char loader_naming_tag[\fBLOADER_NAMING_TAG_SIZE\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
