.TH "loader_initialization_order" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_initialization_order
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_manager_impl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "\fBplugin\fP \fBp\fP"
.br
.ti -1c
.RI "int \fBbeing_deleted\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint64_t loader_initialization_order::id"

.SS "\fBplugin\fP loader_initialization_order::p"

.SS "int loader_initialization_order::being_deleted"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
