.TH "loader_impl_export" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_export
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/loader/include/loader/loader_export\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBloader_impl_descriptor_singleton\fP \fBdescriptor\fP"
.br
.ti -1c
.RI "\fBloader_impl_interface_singleton\fP \fBinterface\fP"
.br
.ti -1c
.RI "\fBloader_impl_print_singleton\fP \fBprint\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBloader_impl_descriptor_singleton\fP loader_impl_export::descriptor"
Loader descriptor reference 
.SS "\fBloader_impl_interface_singleton\fP loader_impl_export::interface"
Loader interface reference 
.SS "\fBloader_impl_print_singleton\fP loader_impl_export::print"
Loader print information callback 

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
