.TH "loader_naming.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_naming.h
.SH SYNOPSIS
.br
.PP
\fC#include <loader/loader_api\&.h>\fP
.br
\fC#include <portability/portability_path\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOADER_PATH_SIZE\fP   PORTABILITY_PATH_SIZE"
.br
.ti -1c
.RI "#define \fBLOADER_NAME_SIZE\fP   0xFF"
.br
.ti -1c
.RI "#define \fBLOADER_TAG_SIZE\fP   0x40"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBloader_path\fP[\fBLOADER_PATH_SIZE\fP]"
.br
.ti -1c
.RI "typedef char \fBloader_name\fP[\fBLOADER_NAME_SIZE\fP]"
.br
.ti -1c
.RI "typedef char \fBloader_tag\fP[\fBLOADER_TAG_SIZE\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOADER_PATH_SIZE   PORTABILITY_PATH_SIZE"

.SS "#define LOADER_NAME_SIZE   0xFF"

.SS "#define LOADER_TAG_SIZE   0x40"

.SH "Typedef Documentation"
.PP 
.SS "typedef char loader_path[\fBLOADER_PATH_SIZE\fP]"

.SS "typedef char loader_name[\fBLOADER_NAME_SIZE\fP]"

.SS "typedef char loader_tag[\fBLOADER_TAG_SIZE\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
