.TH "loader_function.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_function.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBloader_function\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBloader_function\fP"

.PP
Generic loader function reference\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
