.TH "loader_path.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_path.h
.SH SYNOPSIS
.br
.PP
\fC#include <loader/loader_api\&.h>\fP
.br
\fC#include <loader/loader_naming\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_name\fP (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_fullname\fP (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_extension\fP (const \fBloader_naming_path\fP path, \fBloader_naming_tag\fP extension)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_module_name\fP (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name, const \fBloader_naming_tag\fP extension)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_path\fP (const \fBloader_naming_path\fP path, size_t size, \fBloader_naming_path\fP absolute)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_get_relative\fP (const \fBloader_naming_path\fP base, const \fBloader_naming_path\fP path, \fBloader_naming_path\fP relative)"
.br
.ti -1c
.RI "LOADER_API int \fBloader_path_is_absolute\fP (const \fBloader_naming_path\fP path)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_join\fP (const \fBloader_naming_path\fP left_path, size_t left_path_size, const \fBloader_naming_path\fP right_path, size_t right_path_size, \fBloader_naming_path\fP join_path)"
.br
.ti -1c
.RI "LOADER_API size_t \fBloader_path_canonical\fP (const \fBloader_naming_path\fP path, size_t size, \fBloader_naming_path\fP canonical)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LOADER_API size_t loader_path_get_name (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name)"

.SS "LOADER_API size_t loader_path_get_fullname (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name)"

.SS "LOADER_API size_t loader_path_get_extension (const \fBloader_naming_path\fP path, \fBloader_naming_tag\fP extension)"

.SS "LOADER_API size_t loader_path_get_module_name (const \fBloader_naming_path\fP path, \fBloader_naming_name\fP name, const \fBloader_naming_tag\fP extension)"

.SS "LOADER_API size_t loader_path_get_path (const \fBloader_naming_path\fP path, size_t size, \fBloader_naming_path\fP absolute)"

.SS "LOADER_API size_t loader_path_get_relative (const \fBloader_naming_path\fP base, const \fBloader_naming_path\fP path, \fBloader_naming_path\fP relative)"

.SS "LOADER_API int loader_path_is_absolute (const \fBloader_naming_path\fP path)"

.SS "LOADER_API size_t loader_path_join (const \fBloader_naming_path\fP left_path, size_t left_path_size, const \fBloader_naming_path\fP right_path, size_t right_path_size, \fBloader_naming_path\fP join_path)"

.SS "LOADER_API size_t loader_path_canonical (const \fBloader_naming_path\fP path, size_t size, \fBloader_naming_path\fP canonical)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
