.TH "loader_impl_print.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_print.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBloader_impl_print\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBloader_impl_print_info\fP) (void)"
.br
.ti -1c
.RI "typedef loader_impl_print(* \fBloader_impl_print_singleton\fP) (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* loader_impl_print_info) (void)"

.SS "typedef loader_impl_print(* loader_impl_print_singleton) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
