.TH "log.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_level\&.h>\fP
.br
\fC#include <log/log_policy\&.h>\fP
.br
\fC#include <log/log_policy_format\&.h>\fP
.br
\fC#include <log/log_policy_schedule\&.h>\fP
.br
\fC#include <log/log_policy_storage\&.h>\fP
.br
\fC#include <log/log_policy_stream\&.h>\fP
.br
\fC#include <log/log_preprocessor\&.h>\fP
.br
\fC#include <log/log_record\&.h>\fP
.br
\fC#include <format/format_specifier\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API void * \fBlog_instance\fP (void)"
.br
.ti -1c
.RI "LOG_API size_t \fBlog_size\fP (void)"
.br
.ti -1c
.RI "LOG_API int \fBlog_create\fP (const char *name)"
.br
.ti -1c
.RI "LOG_API int \fBlog_define\fP (const char *name, \fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API int \fBlog_configure_impl\fP (const char *name, size_t size,\&.\&.\&.)"
.br
.ti -1c
.RI "LOG_API int \fBlog_level\fP (const char *name, const char *level, size_t length)"
.br
.ti -1c
.RI "LOG_API int \fBlog_write_impl\fP (const char *name, const size_t line, const char *func, const char *\fBfile\fP, const enum \fBlog_level_id\fP level, const char *message)"
.br
.ti -1c
.RI "LOG_API int \fBlog_write_impl_va\fP (const char *name, const size_t line, const char *func, const char *\fBfile\fP, const enum \fBlog_level_id\fP level, const char *message,\&.\&.\&.)"
.br
.ti -1c
.RI "LOG_API int \fBlog_clear\fP (const char *name)"
.br
.ti -1c
.RI "LOG_API int \fBlog_delete\fP (const char *name)"
.br
.ti -1c
.RI "const LOG_API char * \fBlog_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LOG_API void* log_instance (void)"

.SS "LOG_API size_t log_size (void)"

.SS "LOG_API int log_create (const char * name)"

.SS "LOG_API int log_define (const char * name, \fBlog_policy\fP policy)"

.SS "LOG_API int log_configure_impl (const char * name, size_t size,  \&.\&.\&.)"

.SS "LOG_API int log_level (const char * name, const char * level, size_t length)"

.SS "LOG_API int log_write_impl (const char * name, const size_t line, const char * func, const char * file, const enum \fBlog_level_id\fP level, const char * message)"

.SS "LOG_API int log_write_impl_va (const char * name, const size_t line, const char * func, const char * file, const enum \fBlog_level_id\fP level, const char * message,  \&.\&.\&.)"

.SS "LOG_API int log_clear (const char * name)"

.SS "LOG_API int log_delete (const char * name)"

.SS "const LOG_API char* log_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
