.TH "log_policy_schedule_async.h" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_schedule_async.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_policy\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API log_policy_interface \fBlog_policy_schedule_async_interface\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LOG_API log_policy_interface log_policy_schedule_async_interface (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
