.TH "log_policy_stream_nginx_ctor" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_stream_nginx_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_stream_nginx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBngx_log_t\fP * \fBngx_log_ptr\fP"
.br
.ti -1c
.RI "void(* \fBngx_error_ptr\fP )()"
.br
.ti -1c
.RI "uint16_t \fBngx_log_level\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBngx_log_t\fP* log_policy_stream_nginx_ctor::ngx_log_ptr"

.SS "void(* log_policy_stream_nginx_ctor::ngx_error_ptr) ()"

.SS "uint16_t log_policy_stream_nginx_ctor::ngx_log_level"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
