.TH "log_record_ctor" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_record_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_record\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBline\fP"
.br
.ti -1c
.RI "const char * \fBfunc\fP"
.br
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "enum \fBlog_level_id\fP \fBlevel\fP"
.br
.ti -1c
.RI "const char * \fBmessage\fP"
.br
.ti -1c
.RI "struct \fBlog_record_va_list_type\fP * \fBvariable_args\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t log_record_ctor::line"

.SS "const char* log_record_ctor::func"

.SS "const char* log_record_ctor::file"

.SS "enum \fBlog_level_id\fP log_record_ctor::level"

.SS "const char* log_record_ctor::message"

.SS "struct \fBlog_record_va_list_type\fP* log_record_ctor::variable_args"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
