.TH "log_policy.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_aspect\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlog_policy_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef size_t \fBlog_policy_id\fP"
.br
.ti -1c
.RI "typedef void * \fBlog_policy_impl\fP"
.br
.ti -1c
.RI "typedef void * \fBlog_policy_data\fP"
.br
.ti -1c
.RI "typedef void * \fBlog_policy_ctor\fP"
.br
.ti -1c
.RI "typedef int(* \fBlog_policy_interface_create\fP) (\fBlog_policy\fP, const \fBlog_policy_ctor\fP)"
.br
.ti -1c
.RI "typedef int(* \fBlog_policy_interface_destroy\fP) (\fBlog_policy\fP)"
.br
.ti -1c
.RI "typedef log_policy_interface(* \fBlog_policy_singleton\fP) (void)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API \fBlog_policy\fP \fBlog_policy_create\fP (enum \fBlog_aspect_id\fP aspect_id, const log_policy_interface iface, const \fBlog_policy_ctor\fP ctor)"
.br
.ti -1c
.RI "LOG_API void \fBlog_policy_instantiate\fP (\fBlog_policy\fP policy, \fBlog_policy_data\fP instance, const \fBlog_policy_id\fP id)"
.br
.ti -1c
.RI "LOG_API void \fBlog_policy_classify\fP (\fBlog_policy\fP policy, \fBlog_aspect\fP aspect)"
.br
.ti -1c
.RI "LOG_API \fBlog_aspect\fP \fBlog_policy_aspect\fP (\fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API enum \fBlog_aspect_id\fP \fBlog_policy_aspect_id\fP (\fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy_data\fP \fBlog_policy_instance\fP (\fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API log_policy_interface \fBlog_policy_behavior\fP (\fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy_impl\fP \fBlog_policy_derived\fP (\fBlog_policy\fP policy)"
.br
.ti -1c
.RI "LOG_API int \fBlog_policy_destroy\fP (\fBlog_policy\fP policy)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef size_t \fBlog_policy_id\fP"

.SS "typedef void* \fBlog_policy_impl\fP"

.SS "typedef void* \fBlog_policy_data\fP"

.SS "typedef void* \fBlog_policy_ctor\fP"

.SS "typedef int(* log_policy_interface_create) (\fBlog_policy\fP, const \fBlog_policy_ctor\fP)"

.SS "typedef int(* log_policy_interface_destroy) (\fBlog_policy\fP)"

.SS "typedef log_policy_interface(* log_policy_singleton) (void)"

.SH "Function Documentation"
.PP 
.SS "LOG_API \fBlog_policy\fP log_policy_create (enum \fBlog_aspect_id\fP aspect_id, const log_policy_interface iface, const \fBlog_policy_ctor\fP ctor)"

.SS "LOG_API void log_policy_instantiate (\fBlog_policy\fP policy, \fBlog_policy_data\fP instance, const \fBlog_policy_id\fP id)"

.SS "LOG_API void log_policy_classify (\fBlog_policy\fP policy, \fBlog_aspect\fP aspect)"

.SS "LOG_API \fBlog_aspect\fP log_policy_aspect (\fBlog_policy\fP policy)"

.SS "LOG_API enum \fBlog_aspect_id\fP log_policy_aspect_id (\fBlog_policy\fP policy)"

.SS "LOG_API \fBlog_policy_data\fP log_policy_instance (\fBlog_policy\fP policy)"

.SS "LOG_API log_policy_interface log_policy_behavior (\fBlog_policy\fP policy)"

.SS "LOG_API \fBlog_policy_impl\fP log_policy_derived (\fBlog_policy\fP policy)"

.SS "LOG_API int log_policy_destroy (\fBlog_policy\fP policy)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
