.TH "log_aspect_stream.h" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_aspect_stream.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_aspect\&.h>\fP
.br
\fC#include <log/log_handle\&.h>\fP
.br
\fC#include <log/log_record\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlog_aspect_stream_impl\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBlog_aspect_stream_write\fP) (\fBlog_aspect\fP, const log_record_ctor)"
.br
.ti -1c
.RI "typedef int(* \fBlog_aspect_stream_flush\fP) (\fBlog_aspect\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API log_aspect_interface \fBlog_aspect_stream_interface\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* log_aspect_stream_write) (\fBlog_aspect\fP, const log_record_ctor)"

.SS "typedef int(* log_aspect_stream_flush) (\fBlog_aspect\fP)"

.SH "Function Documentation"
.PP 
.SS "LOG_API log_aspect_interface log_aspect_stream_interface (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
