.TH "log_policy_interface" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_policy_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBlog_policy_impl\fP \fBimpl\fP"
.br
.ti -1c
.RI "\fBlog_policy_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlog_policy_interface_create\fP log_policy_interface::create"

.SS "\fBlog_policy_impl\fP log_policy_interface::impl"

.SS "\fBlog_policy_interface_destroy\fP log_policy_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
