.TH "log_policy_stream_socket_ctor" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_stream_socket_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_stream_socket\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBip\fP"
.br
.ti -1c
.RI "uint16_t \fBport\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* log_policy_stream_socket_ctor::ip"

.SS "uint16_t log_policy_stream_socket_ctor::port"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
