.TH "log_policy_format_custom_va_list" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_format_custom_va_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_format_custom\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "va_list \fBva\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "va_list log_policy_format_custom_va_list::va"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
