.TH "log_policy_format.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_format.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_policy\&.h>\fP
.br
\fC#include <log/log_policy_format_binary\&.h>\fP
.br
\fC#include <log/log_policy_format_custom\&.h>\fP
.br
\fC#include <log/log_policy_format_text\&.h>\fP
.br
\fC#include <log/log_record\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlog_policy_format_impl\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef size_t(* \fBlog_policy_format_size\fP) (\fBlog_policy\fP, const \fBlog_record\fP)"
.br
.ti -1c
.RI "typedef size_t(* \fBlog_policy_format_serialize\fP) (\fBlog_policy\fP, const \fBlog_record\fP, void *, const size_t)"
.br
.ti -1c
.RI "typedef size_t(* \fBlog_policy_format_deserialize\fP) (\fBlog_policy\fP, \fBlog_record\fP, const void *, const size_t)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlog_policy_format_id\fP { \fBLOG_POLICY_FORMAT_BINARY\fP = 0x00, \fBLOG_POLICY_FORMAT_TEXT\fP = 0x01, \fBLOG_POLICY_FORMAT_CUSTOM\fP = 0x02, \fBLOG_POLICY_FORMAT_SIZE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API log_policy_interface \fBlog_policy_format\fP (const \fBlog_policy_id\fP policy_format_id)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy\fP \fBlog_policy_format_binary\fP (void)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy\fP \fBlog_policy_format_text\fP (void)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy\fP \fBlog_policy_format_text_flags\fP (unsigned int flags)"
.br
.ti -1c
.RI "LOG_API \fBlog_policy\fP \fBlog_policy_format_custom\fP (void *\fBcontext\fP, \fBlog_policy_format_custom_size_ptr\fP format_size, \fBlog_policy_format_custom_serialize_ptr\fP format_serialize, \fBlog_policy_format_custom_deserialize_ptr\fP format_deserialize)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef size_t(* log_policy_format_size) (\fBlog_policy\fP, const \fBlog_record\fP)"

.SS "typedef size_t(* log_policy_format_serialize) (\fBlog_policy\fP, const \fBlog_record\fP, void *, const size_t)"

.SS "typedef size_t(* log_policy_format_deserialize) (\fBlog_policy\fP, \fBlog_record\fP, const void *, const size_t)"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlog_policy_format_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOG_POLICY_FORMAT_BINARY \fP\fP
.TP
\fB\fILOG_POLICY_FORMAT_TEXT \fP\fP
.TP
\fB\fILOG_POLICY_FORMAT_CUSTOM \fP\fP
.TP
\fB\fILOG_POLICY_FORMAT_SIZE \fP\fP
.SH "Function Documentation"
.PP 
.SS "LOG_API log_policy_interface log_policy_format (const \fBlog_policy_id\fP policy_format_id)"

.SS "LOG_API \fBlog_policy\fP log_policy_format_binary (void)"

.SS "LOG_API \fBlog_policy\fP log_policy_format_text (void)"

.SS "LOG_API \fBlog_policy\fP log_policy_format_text_flags (unsigned int flags)"

.SS "LOG_API \fBlog_policy\fP log_policy_format_custom (void * context, \fBlog_policy_format_custom_size_ptr\fP format_size, \fBlog_policy_format_custom_serialize_ptr\fP format_serialize, \fBlog_policy_format_custom_deserialize_ptr\fP format_deserialize)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
