.TH "log_policy_stream_custom_ctor" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_stream_custom_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_stream_custom\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBcontext\fP"
.br
.ti -1c
.RI "int(* \fBstream_write\fP )(void *, const char *, const size_t)"
.br
.ti -1c
.RI "int(* \fBstream_flush\fP )(void *)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* log_policy_stream_custom_ctor::context"

.SS "int(* log_policy_stream_custom_ctor::stream_write) (void *, const char *, const size_t)"

.SS "int(* log_policy_stream_custom_ctor::stream_flush) (void *)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
