.TH "log_singleton.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_singleton.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_impl\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct log_singleton_map_bucket_type * \fBlog_singleton_map_bucket\fP"
.br
.ti -1c
.RI "typedef struct log_singleton_type * \fBlog_singleton\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API \fBlog_singleton\fP * \fBlog_singleton_instance\fP (void)"
.br
.ti -1c
.RI "LOG_API void \fBlog_singleton_initialize\fP (\fBlog_singleton\fP singleton)"
.br
.ti -1c
.RI "LOG_API size_t \fBlog_singleton_size\fP (void)"
.br
.ti -1c
.RI "LOG_API int \fBlog_singleton_insert\fP (const char *name, \fBlog_impl\fP impl)"
.br
.ti -1c
.RI "LOG_API \fBlog_impl\fP \fBlog_singleton_get\fP (const char *name)"
.br
.ti -1c
.RI "LOG_API \fBlog_impl\fP \fBlog_singleton_remove\fP (const char *name)"
.br
.ti -1c
.RI "LOG_API void \fBlog_singleton_clear\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct log_singleton_map_bucket_type* \fBlog_singleton_map_bucket\fP"

.SS "typedef struct log_singleton_type* \fBlog_singleton\fP"

.SH "Function Documentation"
.PP 
.SS "LOG_API \fBlog_singleton\fP* log_singleton_instance (void)"

.SS "LOG_API void log_singleton_initialize (\fBlog_singleton\fP singleton)"

.SS "LOG_API size_t log_singleton_size (void)"

.SS "LOG_API int log_singleton_insert (const char * name, \fBlog_impl\fP impl)"

.SS "LOG_API \fBlog_impl\fP log_singleton_get (const char * name)"

.SS "LOG_API \fBlog_impl\fP log_singleton_remove (const char * name)"

.SS "LOG_API void log_singleton_clear (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
