.TH "log_aspect_format_impl" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_aspect_format_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_aspect_format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_aspect_format_size\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBlog_aspect_format_serialize\fP \fBserialize\fP"
.br
.ti -1c
.RI "\fBlog_aspect_format_deserialize\fP \fBdeserialize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlog_aspect_format_size\fP log_aspect_format_impl::size"

.SS "\fBlog_aspect_format_serialize\fP log_aspect_format_impl::serialize"

.SS "\fBlog_aspect_format_deserialize\fP log_aspect_format_impl::deserialize"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
