.TH "log_record_va_list_type" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_record_va_list_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_record\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "va_list \fBdata\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "va_list log_record_va_list_type::data"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
