.TH "log_aspect_schedule.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_aspect_schedule.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_aspect\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlog_aspect_schedule_impl\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBlog_aspect_schedule_data\fP"
.br
.ti -1c
.RI "typedef int(* \fBlog_aspect_schedule_execute_cb\fP) (\fBlog_policy\fP, \fBlog_aspect_schedule_data\fP)"
.br
.ti -1c
.RI "typedef int(* \fBlog_aspect_schedule_execute\fP) (\fBlog_aspect\fP, \fBlog_aspect_schedule_execute_cb\fP, \fBlog_aspect_schedule_data\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API log_aspect_interface \fBlog_aspect_schedule_interface\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBlog_aspect_schedule_data\fP"

.SS "typedef int(* log_aspect_schedule_execute_cb) (\fBlog_policy\fP, \fBlog_aspect_schedule_data\fP)"

.SS "typedef int(* log_aspect_schedule_execute) (\fBlog_aspect\fP, \fBlog_aspect_schedule_execute_cb\fP, \fBlog_aspect_schedule_data\fP)"

.SH "Function Documentation"
.PP 
.SS "LOG_API log_aspect_interface log_aspect_schedule_interface (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
