.TH "log_aspect_stream_impl" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_aspect_stream_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_aspect_stream\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_aspect_stream_write\fP \fBwrite\fP"
.br
.ti -1c
.RI "\fBlog_aspect_stream_flush\fP \fBflush\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlog_aspect_stream_write\fP log_aspect_stream_impl::write"

.SS "\fBlog_aspect_stream_flush\fP log_aspect_stream_impl::flush"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
