.TH "log_policy_storage_sequential.h" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_storage_sequential.h
.SH SYNOPSIS
.br
.PP
\fC#include <log/log_api\&.h>\fP
.br
\fC#include <log/log_policy\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "LOG_API log_policy_interface \fBlog_policy_storage_sequential_interface\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "LOG_API log_policy_interface log_policy_storage_sequential_interface (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
