.TH "log_policy_format_impl" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_format_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_policy_format_size\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBlog_policy_format_serialize\fP \fBserialize\fP"
.br
.ti -1c
.RI "\fBlog_policy_format_deserialize\fP \fBdeserialize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlog_policy_format_size\fP log_policy_format_impl::size"

.SS "\fBlog_policy_format_serialize\fP log_policy_format_impl::serialize"

.SS "\fBlog_policy_format_deserialize\fP log_policy_format_impl::deserialize"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
