.TH "log_policy_stream_stdio_ctor" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_stream_stdio_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_policy_stream_stdio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBstream\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "FILE* log_policy_stream_stdio_ctor::stream"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
