.TH "log_aspect_storage_impl" 3 "Tue Jan 23 2024" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_aspect_storage_impl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/log/include/log/log_aspect_storage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlog_aspect_storage_append\fP \fBappend\fP"
.br
.ti -1c
.RI "\fBlog_aspect_storage_flush\fP \fBflush\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBlog_aspect_storage_append\fP log_aspect_storage_impl::append"

.SS "\fBlog_aspect_storage_flush\fP log_aspect_storage_impl::flush"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
