.TH "metacall_await_callbacks" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_await_callbacks
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmetacall_await_callback\fP \fBresolve\fP"
.br
.ti -1c
.RI "\fBmetacall_await_callback\fP \fBreject\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmetacall_await_callback\fP metacall_await_callbacks::resolve"

.SS "\fBmetacall_await_callback\fP metacall_await_callbacks::reject"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
