.TH "metacall_log_custom_va_list" 3 "Wed Jun 30 2021" "Version 0.1.0.9bcc4c97acac" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_log_custom_va_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall_log\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "va_list \fBva\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "va_list metacall_log_custom_va_list::va"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
