.TH "metacall_version_type" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_version_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmajor\fP"
.br
.ti -1c
.RI "unsigned int \fBminor\fP"
.br
.ti -1c
.RI "unsigned int \fBpatch\fP"
.br
.ti -1c
.RI "const char * \fBrevision\fP"
.br
.ti -1c
.RI "const char * \fBstr\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int metacall_version_type::major"

.SS "unsigned int metacall_version_type::minor"

.SS "unsigned int metacall_version_type::patch"

.SS "const char* metacall_version_type::revision"

.SS "const char* metacall_version_type::str"

.SS "const char* metacall_version_type::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
