.TH "metacall_log_syslog" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_log_syslog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall_log\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* metacall_log_syslog::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
