.TH "metacall_initialize_configuration_type" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_initialize_configuration_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBtag\fP"
.br
.ti -1c
.RI "void * \fBoptions\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* metacall_initialize_configuration_type::tag"

.SS "void* metacall_initialize_configuration_type::options"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
