.TH "metacall_log_custom" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall_log_custom
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/metacall/include/metacall/metacall_log\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBcontext\fP"
.br
.ti -1c
.RI "size_t(* \fBformat_size\fP )(void *, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"
.br
.ti -1c
.RI "size_t(* \fBformat_serialize\fP )(void *, void *, const size_t, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"
.br
.ti -1c
.RI "size_t(* \fBformat_deserialize\fP )(void *, const void *, const size_t, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"
.br
.ti -1c
.RI "int(* \fBstream_write\fP )(void *, const char *, const size_t)"
.br
.ti -1c
.RI "int(* \fBstream_flush\fP )(void *)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* metacall_log_custom::context"

.SS "size_t(* metacall_log_custom::format_size) (void *, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"

.SS "size_t(* metacall_log_custom::format_serialize) (void *, void *, const size_t, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"

.SS "size_t(* metacall_log_custom::format_deserialize) (void *, const void *, const size_t, const char *, size_t, size_t, const char *, const char *, const char *, const char *, metacall_log_custom_va_list)"

.SS "int(* metacall_log_custom::stream_write) (void *, const char *, const size_t)"

.SS "int(* metacall_log_custom::stream_flush) (void *)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
