.TH "object_interface" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBobject_impl_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_get\fP \fBget\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_set\fP \fBset\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_method_invoke\fP \fBmethod_invoke\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_method_await\fP \fBmethod_await\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_destructor\fP \fBdestructor\fP"
.br
.ti -1c
.RI "\fBobject_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBobject_impl_interface_create\fP object_interface::create"

.SS "\fBobject_impl_interface_get\fP object_interface::get"

.SS "\fBobject_impl_interface_set\fP object_interface::set"

.SS "\fBobject_impl_interface_method_invoke\fP object_interface::method_invoke"

.SS "\fBobject_impl_interface_method_await\fP object_interface::method_await"

.SS "\fBobject_impl_interface_destructor\fP object_interface::destructor"

.SS "\fBobject_impl_interface_destroy\fP object_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
