.TH "plugin_manager" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugin_manager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/plugin/include/plugin/plugin_manager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBlibrary_path\fP"
.br
.ti -1c
.RI "\fBset\fP \fBplugins\fP"
.br
.ti -1c
.RI "plugin_manager_interface \fBiface\fP"
.br
.ti -1c
.RI "void * \fBimpl\fP"
.br
.ti -1c
.RI "\fBplugin_loader\fP \fBl\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* plugin_manager::name"

.SS "char* plugin_manager::library_path"

.SS "\fBset\fP plugin_manager::plugins"

.SS "plugin_manager_interface plugin_manager::iface"

.SS "void* plugin_manager::impl"

.SS "\fBplugin_loader\fP plugin_manager::l"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
