.TH "plugin_descriptor.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugin_descriptor.h
.SH SYNOPSIS
.br
.PP
\fC#include <plugin/plugin_api\&.h>\fP
.br
\fC#include <dynlink/dynlink\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBplugin_descriptor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "PLUGIN_API plugin_descriptor \fBplugin_descriptor_create\fP (char *path, char *library_name, char *symbol_iface_name)"
.br
.ti -1c
.RI "PLUGIN_API void \fBplugin_descriptor_destroy\fP (plugin_descriptor descriptor)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PLUGIN_API plugin_descriptor plugin_descriptor_create (char * path, char * library_name, char * symbol_iface_name)"

.SS "PLUGIN_API void plugin_descriptor_destroy (plugin_descriptor descriptor)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
