.TH "plugin_descriptor" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugin_descriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/plugin/include/plugin/plugin_descriptor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdynlink\fP \fBhandle\fP"
.br
.ti -1c
.RI "char * \fBlibrary_name\fP"
.br
.ti -1c
.RI "char * \fBsymbol_iface_name\fP"
.br
.ti -1c
.RI "void *(* \fBiface_singleton\fP )(void)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBdynlink\fP plugin_descriptor::handle"

.SS "char* plugin_descriptor::library_name"

.SS "char* plugin_descriptor::symbol_iface_name"

.SS "void*(* plugin_descriptor::iface_singleton) (void)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
