.TH "plugin.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plugin.h
.SH SYNOPSIS
.br
.PP
\fC#include <plugin/plugin_api\&.h>\fP
.br
\fC#include <plugin/plugin_manager\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "PLUGIN_API const char * \fBplugin_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PLUGIN_API const char* plugin_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
