.TH "preprocessor_comma.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor_comma.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_empty\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_if\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPREPROCESSOR_COMMA_SYMBOL\fP()   ,"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMMA_IF_IMPL\fP(expr)   	\fBPREPROCESSOR_IF\fP(expr, \fBPREPROCESSOR_COMMA_SYMBOL\fP, \fBPREPROCESSOR_EMPTY_SYMBOL\fP)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMMA_IF\fP(expr)   	\fBPREPROCESSOR_COMMA_IF_IMPL\fP(expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMMA_VARIADIC\fP(\&.\&.\&.)   ,"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PREPROCESSOR_COMMA_SYMBOL()   ,"

.SS "#define PREPROCESSOR_COMMA_IF_IMPL(expr)   	\fBPREPROCESSOR_IF\fP(expr, \fBPREPROCESSOR_COMMA_SYMBOL\fP, \fBPREPROCESSOR_EMPTY_SYMBOL\fP)"

.SS "#define PREPROCESSOR_COMMA_IF(expr)   	\fBPREPROCESSOR_COMMA_IF_IMPL\fP(expr)"

.SS "#define PREPROCESSOR_COMMA_VARIADIC( \&.\&.\&.)   ,"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
