.TH "preprocessor.h" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_arguments\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_arithmetic\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_bit\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_boolean\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_comma\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_comparison\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_complement\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_concatenation\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_detection\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_empty\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_for\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_if\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_serial\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_stringify\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_tuple\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const PREPROCESSOR_API char * \fBpreprocessor_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const PREPROCESSOR_API char* preprocessor_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
