.TH "preprocessor_empty.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor_empty.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPREPROCESSOR_EMPTY_SYMBOL\fP()"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_EMPTY_EXPANSION\fP(expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_EMPTY_EXPANSION_VARIADIC\fP(\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PREPROCESSOR_EMPTY_SYMBOL()"

.SS "#define PREPROCESSOR_EMPTY_EXPANSION(expr)"

.SS "#define PREPROCESSOR_EMPTY_EXPANSION_VARIADIC( \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
