.TH "preprocessor_bit.h" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor_bit.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_complement\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_concatenation\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_AND_IMPL_0\fP(expr)   0"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_AND_IMPL_1\fP(expr)   expr"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_OR_IMPL_0\fP(expr)   expr"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_OR_IMPL_1\fP(expr)   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_XOR_IMPL_0\fP(expr)   expr"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_XOR_IMPL_1\fP(expr)   \fBPREPROCESSOR_COMPL\fP(expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_AND\fP(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_AND_IMPL_, expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_OR\fP(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_OR_IMPL_, expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BIT_XOR\fP(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_XOR_IMPL_, expr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PREPROCESSOR_BIT_AND_IMPL_0(expr)   0"

.SS "#define PREPROCESSOR_BIT_AND_IMPL_1(expr)   expr"

.SS "#define PREPROCESSOR_BIT_OR_IMPL_0(expr)   expr"

.SS "#define PREPROCESSOR_BIT_OR_IMPL_1(expr)   1"

.SS "#define PREPROCESSOR_BIT_XOR_IMPL_0(expr)   expr"

.SS "#define PREPROCESSOR_BIT_XOR_IMPL_1(expr)   \fBPREPROCESSOR_COMPL\fP(expr)"

.SS "#define PREPROCESSOR_BIT_AND(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_AND_IMPL_, expr)"

.SS "#define PREPROCESSOR_BIT_OR(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_OR_IMPL_, expr)"

.SS "#define PREPROCESSOR_BIT_XOR(expr)   \fBPREPROCESSOR_CONCAT\fP(PREPROCESSOR_BIT_XOR_IMPL_, expr)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
