.TH "preprocessor_complement.h" 3 "Sat Jun 26 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor_complement.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPREPROCESSOR_COMPL_IMPL_0\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMPL_IMPL_1\fP   0"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMPL_IMPL\fP(expr)   PREPROCESSOR_COMPL_IMPL_##expr"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_COMPL\fP(expr)   \fBPREPROCESSOR_COMPL_IMPL\fP(expr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PREPROCESSOR_COMPL_IMPL_0   1"

.SS "#define PREPROCESSOR_COMPL_IMPL_1   0"

.SS "#define PREPROCESSOR_COMPL_IMPL(expr)   PREPROCESSOR_COMPL_IMPL_##expr"

.SS "#define PREPROCESSOR_COMPL(expr)   \fBPREPROCESSOR_COMPL_IMPL\fP(expr)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
