.TH "preprocessor_boolean.h" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preprocessor_boolean.h
.SH SYNOPSIS
.br
.PP
\fC#include <preprocessor/preprocessor_api\&.h>\fP
.br
\fC#include <preprocessor/preprocessor_complement\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_SIZE\fP   256"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_0\fP   0"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_1\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_2\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_3\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_4\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_5\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_6\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_7\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_8\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_9\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_10\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_11\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_12\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_13\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_14\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_15\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_16\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_17\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_18\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_19\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_20\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_21\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_22\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_23\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_24\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_25\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_26\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_27\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_28\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_29\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_30\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_31\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_32\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_33\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_34\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_35\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_36\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_37\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_38\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_39\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_40\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_41\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_42\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_43\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_44\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_45\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_46\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_47\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_48\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_49\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_50\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_51\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_52\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_53\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_54\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_55\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_56\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_57\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_58\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_59\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_60\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_61\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_62\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_63\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_64\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_65\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_66\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_67\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_68\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_69\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_70\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_71\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_72\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_73\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_74\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_75\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_76\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_77\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_78\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_79\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_80\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_81\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_82\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_83\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_84\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_85\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_86\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_87\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_88\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_89\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_90\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_91\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_92\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_93\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_94\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_95\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_96\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_97\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_98\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_99\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_100\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_101\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_102\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_103\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_104\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_105\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_106\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_107\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_108\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_109\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_110\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_111\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_112\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_113\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_114\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_115\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_116\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_117\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_118\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_119\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_120\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_121\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_122\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_123\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_124\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_125\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_126\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_127\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_128\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_129\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_130\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_131\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_132\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_133\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_134\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_135\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_136\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_137\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_138\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_139\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_140\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_141\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_142\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_143\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_144\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_145\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_146\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_147\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_148\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_149\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_150\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_151\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_152\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_153\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_154\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_155\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_156\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_157\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_158\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_159\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_160\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_161\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_162\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_163\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_164\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_165\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_166\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_167\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_168\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_169\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_170\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_171\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_172\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_173\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_174\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_175\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_176\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_177\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_178\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_179\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_180\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_181\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_182\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_183\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_184\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_185\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_186\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_187\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_188\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_189\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_190\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_191\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_192\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_193\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_194\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_195\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_196\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_197\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_198\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_199\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_200\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_201\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_202\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_203\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_204\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_205\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_206\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_207\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_208\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_209\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_210\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_211\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_212\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_213\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_214\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_215\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_216\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_217\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_218\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_219\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_220\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_221\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_222\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_223\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_224\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_225\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_226\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_227\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_228\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_229\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_230\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_231\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_232\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_233\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_234\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_235\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_236\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_237\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_238\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_239\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_240\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_241\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_242\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_243\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_244\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_245\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_246\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_247\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_248\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_249\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_250\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_251\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_252\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_253\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_254\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_255\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL_256\fP   1"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL_IMPL\fP(expr)   PREPROCESSOR_BOOL_IMPL_ ## expr"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_BOOL\fP(expr)   \fBPREPROCESSOR_BOOL_IMPL\fP(expr)"
.br
.ti -1c
.RI "#define \fBPREPROCESSOR_NOT\fP(expr)   \fBPREPROCESSOR_COMPL\fP(\fBPREPROCESSOR_BOOL\fP(expr))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PREPROCESSOR_BOOL_SIZE   256"

.SS "#define PREPROCESSOR_BOOL_IMPL_0   0"

.SS "#define PREPROCESSOR_BOOL_IMPL_1   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_2   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_3   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_4   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_5   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_6   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_7   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_8   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_9   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_10   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_11   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_12   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_13   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_14   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_15   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_16   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_17   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_18   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_19   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_20   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_21   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_22   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_23   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_24   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_25   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_26   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_27   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_28   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_29   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_30   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_31   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_32   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_33   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_34   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_35   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_36   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_37   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_38   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_39   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_40   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_41   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_42   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_43   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_44   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_45   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_46   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_47   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_48   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_49   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_50   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_51   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_52   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_53   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_54   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_55   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_56   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_57   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_58   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_59   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_60   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_61   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_62   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_63   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_64   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_65   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_66   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_67   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_68   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_69   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_70   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_71   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_72   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_73   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_74   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_75   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_76   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_77   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_78   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_79   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_80   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_81   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_82   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_83   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_84   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_85   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_86   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_87   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_88   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_89   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_90   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_91   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_92   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_93   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_94   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_95   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_96   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_97   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_98   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_99   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_100   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_101   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_102   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_103   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_104   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_105   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_106   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_107   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_108   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_109   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_110   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_111   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_112   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_113   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_114   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_115   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_116   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_117   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_118   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_119   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_120   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_121   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_122   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_123   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_124   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_125   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_126   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_127   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_128   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_129   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_130   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_131   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_132   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_133   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_134   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_135   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_136   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_137   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_138   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_139   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_140   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_141   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_142   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_143   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_144   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_145   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_146   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_147   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_148   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_149   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_150   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_151   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_152   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_153   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_154   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_155   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_156   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_157   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_158   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_159   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_160   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_161   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_162   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_163   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_164   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_165   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_166   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_167   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_168   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_169   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_170   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_171   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_172   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_173   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_174   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_175   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_176   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_177   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_178   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_179   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_180   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_181   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_182   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_183   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_184   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_185   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_186   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_187   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_188   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_189   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_190   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_191   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_192   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_193   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_194   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_195   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_196   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_197   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_198   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_199   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_200   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_201   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_202   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_203   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_204   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_205   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_206   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_207   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_208   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_209   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_210   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_211   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_212   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_213   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_214   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_215   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_216   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_217   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_218   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_219   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_220   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_221   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_222   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_223   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_224   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_225   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_226   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_227   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_228   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_229   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_230   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_231   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_232   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_233   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_234   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_235   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_236   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_237   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_238   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_239   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_240   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_241   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_242   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_243   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_244   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_245   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_246   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_247   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_248   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_249   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_250   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_251   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_252   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_253   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_254   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_255   1"

.SS "#define PREPROCESSOR_BOOL_IMPL_256   1"

.SS "#define PREPROCESSOR_BOOL_IMPL(expr)   PREPROCESSOR_BOOL_IMPL_ ## expr"

.SS "#define PREPROCESSOR_BOOL(expr)   \fBPREPROCESSOR_BOOL_IMPL\fP(expr)"

.SS "#define PREPROCESSOR_NOT(expr)   \fBPREPROCESSOR_COMPL\fP(\fBPREPROCESSOR_BOOL\fP(expr))"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
