.TH "reflect_throwable.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_throwable.h
.SH SYNOPSIS
.br
.PP
\fC#include <reflect/reflect_api\&.h>\fP
.br
\fC#include <reflect/reflect_value\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct throwable_type * \fBthrowable\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "REFLECT_API \fBthrowable\fP \fBthrowable_create\fP (\fBvalue\fP v)"
.br
.ti -1c
.RI "REFLECT_API \fBvalue\fP \fBthrowable_value\fP (\fBthrowable\fP th)"
.br
.ti -1c
.RI "REFLECT_API void \fBthrowable_destroy\fP (\fBthrowable\fP th)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct throwable_type* \fBthrowable\fP"

.SH "Function Documentation"
.PP 
.SS "REFLECT_API \fBthrowable\fP throwable_create (\fBvalue\fP v)"

.SS "REFLECT_API \fBvalue\fP throwable_value (\fBthrowable\fP th)"

.SS "REFLECT_API void throwable_destroy (\fBthrowable\fP th)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
