.TH "reflect_class_decl.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_class_decl.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBclass_impl\fP"
.br
.ti -1c
.RI "typedef struct class_type * \fBklass\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBclass_impl\fP"

.SS "typedef struct class_type* \fBklass\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
