.TH "reflect_constructor_decl.h" 3 "Thu Feb 8 2024" "Version 0.7.7.251ee5582288" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_constructor_decl.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct constructor_type * \fBconstructor\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct constructor_type* \fBconstructor\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
