.TH "reflect.h" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect.h
.SH SYNOPSIS
.br
.PP
\fC#include <reflect/reflect_api\&.h>\fP
.br
\fC#include <reflect/reflect_class\&.h>\fP
.br
\fC#include <reflect/reflect_context\&.h>\fP
.br
\fC#include <reflect/reflect_function\&.h>\fP
.br
\fC#include <reflect/reflect_future\&.h>\fP
.br
\fC#include <reflect/reflect_object\&.h>\fP
.br
\fC#include <reflect/reflect_scope\&.h>\fP
.br
\fC#include <reflect/reflect_signature\&.h>\fP
.br
\fC#include <reflect/reflect_type\&.h>\fP
.br
\fC#include <reflect/reflect_type_id\&.h>\fP
.br
\fC#include <reflect/reflect_value\&.h>\fP
.br
\fC#include <reflect/reflect_value_type\&.h>\fP
.br
\fC#include <reflect/reflect_value_type_cast\&.h>\fP
.br
\fC#include <reflect/reflect_value_type_demotion\&.h>\fP
.br
\fC#include <reflect/reflect_value_type_id_size\&.h>\fP
.br
\fC#include <reflect/reflect_value_type_promotion\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const REFLECT_API char * \fBreflect_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const REFLECT_API char* reflect_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
