.TH "reflect_async.h" 3 "Tue Oct 26 2021" "Version 0.1.0.44b1ab3b98a6" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_async.h
.SH SYNOPSIS
.br
.PP
\fC#include <reflect/reflect_api\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBasync_id\fP { \fBSYNCHRONOUS\fP = 0, \fBASYNCHRONOUS\fP = 1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBasync_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISYNCHRONOUS \fP\fP
.TP
\fB\fIASYNCHRONOUS \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
