.TH "reflect_method_decl.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_method_decl.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmethod_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBmethod_impl\fP"
.br
.ti -1c
.RI "typedef struct method_type * \fBmethod\fP"
.br
.ti -1c
.RI "typedef void(* \fBmethod_impl_interface_destroy\fP) (\fBmethod\fP, \fBmethod_impl\fP)"
.br
.ti -1c
.RI "typedef method_interface(* \fBmethod_impl_interface_singleton\fP) (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBmethod_impl\fP"

.SS "typedef struct method_type* \fBmethod\fP"

.SS "typedef void(* method_impl_interface_destroy) (\fBmethod\fP, \fBmethod_impl\fP)"

.SS "typedef method_interface(* method_impl_interface_singleton) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
