.TH "reflect_attribute_decl.h" 3 "Mon Mar 25 2024" "Version 0.7.11.12f31bd02db2" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_attribute_decl.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBattribute_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBattribute_impl\fP"
.br
.ti -1c
.RI "typedef struct \fBattribute_type\fP * \fBattribute\fP"
.br
.ti -1c
.RI "typedef void(* \fBattribute_impl_interface_destroy\fP) (\fBattribute\fP, \fBattribute_impl\fP)"
.br
.ti -1c
.RI "typedef attribute_interface(* \fBattribute_impl_interface_singleton\fP) (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBattribute_impl\fP"

.SS "typedef struct \fBattribute_type\fP* \fBattribute\fP"

.SS "typedef void(* attribute_impl_interface_destroy) (\fBattribute\fP, \fBattribute_impl\fP)"

.SS "typedef attribute_interface(* attribute_impl_interface_singleton) (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
