.TH "reflect_value_type_id_size.h" 3 "Sat Dec 30 2023" "Version 0.7.5.34b28423138e" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reflect_value_type_id_size.h
.SH SYNOPSIS
.br
.PP
\fC#include <reflect/reflect_api\&.h>\fP
.br
\fC#include <reflect/reflect_type_id\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "REFLECT_API size_t \fBvalue_type_id_size\fP (\fBtype_id\fP id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "REFLECT_API size_t value_type_id_size (\fBtype_id\fP id)"

.PP
Return size of a type by @id\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP Type id used to obtain the size
.RE
.PP
\fBReturns\fP
.RS 4
Size of type assigned to @id 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
