.TH "set_bucket" 3 "Mon Jun 28 2021" "Version 0.1.0.e6cda9765a88" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_bucket
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/adt/include/adt/adt_set_bucket\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "set_pair \fBpairs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t set_bucket::count"

.SS "size_t set_bucket::capacity"

.SS "set_pair set_bucket::pairs"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
