.TH "type_interface" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/landing\-page/landing\-page/core/source/reflect/include/reflect/reflect_type\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtype_impl_interface_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBtype_impl_interface_destroy\fP \fBdestroy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBtype_impl_interface_create\fP type_interface::create"

.SS "\fBtype_impl_interface_destroy\fP type_interface::destroy"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
