.TH "version.h" 3 "Thu Jan 25 2024" "Version 0.7.6.81e303e08d17" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.h
.SH SYNOPSIS
.br
.PP
\fC#include <version/version_api\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "VERSION_API const char * \fBversion_print_info\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "VERSION_API const char* version_print_info (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
